/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: eMPyOrHyG40BuxYeGn+pPDQCwmYEkcY6hXEsjin8ZPD+fVmP5T4EtQFvq8J94KqgKtZm3w5h9NwoFZnhswpm+A==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'
import Node from './node'

interface AvailableEvent {
  became_available: (boolean) | null
  block: Headers['block_number']
  node: Node['pool_address']
}
export default AvailableEvent;

interface AvailableEvent_InsertParameters {
  became_available?: (boolean) | null
  block: Headers['block_number']
  node: Node['pool_address']
}
export type {AvailableEvent_InsertParameters}
