/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: PX4FzmqPfIFrL+fwXlsTXtp+vQKcLeLbaz0PZkDgzpNvogttEgcTlcM7ww75WzE9/nYdJnG8ZJeVh3iDXWfV9Q==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'
import Node from './node'

/**
 * bonus score history of a node
 */
interface BonusScoreHistory {
  bonus_score: number
  from_block: Headers['block_number']
  node: Node['pool_address']
  to_block: (Headers['block_number']) | null
}
export default BonusScoreHistory;

/**
 * bonus score history of a node
 */
interface BonusScoreHistory_InsertParameters {
  bonus_score: number
  from_block: Headers['block_number']
  node: Node['pool_address']
  to_block?: (Headers['block_number']) | null
}
export type {BonusScoreHistory_InsertParameters}
