/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: RLfxbp3FxEX2PGk86kK23R2epg0DOf1WwC12cSj2bdCABQ3Lbd7v2fc7qDAUxWMmq8WRp0ldyZeS0fyTaT7VUg==
 */

/* eslint-disable */
// tslint:disable

import DelegateStaker from './delegate_staker'
import PosdaoEpoch from './posdao_epoch'

/**
 * rewards from delegate staking
 */
interface DelegateReward {
  id_delegator: DelegateStaker['id']
  id_node: Buffer & {readonly __brand?: 'delegate_reward_id_node'}
  id_posdao_epoch: PosdaoEpoch['id']
  /**
   * @default false
   */
  is_claimed: (boolean) | null
  reward_amount: string
}
export default DelegateReward;

/**
 * rewards from delegate staking
 */
interface DelegateReward_InsertParameters {
  id_delegator: DelegateStaker['id']
  id_node: Buffer & {readonly __brand?: 'delegate_reward_id_node'}
  id_posdao_epoch: PosdaoEpoch['id']
  /**
   * @default false
   */
  is_claimed?: (boolean) | null
  reward_amount: string
}
export type {DelegateReward_InsertParameters}
