/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: W+ToUteOYHdPxbhVTMx8WgybAXDfYDOuXHrwccP8Wuoxa+0hMq2mTPnEZcSMx2QEsUsKwafu3HddDGxSKzsU7w==
 */

/* eslint-disable */
// tslint:disable

interface DelegateStaker {
  id: Buffer & {readonly __brand?: 'delegate_staker_id'}
}
export default DelegateStaker;

interface DelegateStaker_InsertParameters {
  id: Buffer & {readonly __brand?: 'delegate_staker_id'}
}
export type {DelegateStaker_InsertParameters}
