/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: zUqcxW+uTBC0Oh/c4oYGVtXhpNu1xDG3AvaliKtHpc3SrTrV/qtTxj3M3bTmtdln99BgvS7FfriDuPP1LKUkwg==
 */

/* eslint-disable */
// tslint:disable

interface DelegateStaker {
  id: string & {readonly __brand?: 'delegate_staker_id'}
}
export default DelegateStaker;

interface DelegateStaker_InsertParameters {
  id: string & {readonly __brand?: 'delegate_staker_id'}
}
export type {DelegateStaker_InsertParameters}
