/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: iejOfAaoKLdawtY+Lc0e1ogpgP2rAM3p2wURjxH2j2UwlMiaQUn0i+7YnzXkmiDwRqQHK2hpq10lQA8iFLqCzQ==
 */

/* eslint-disable */
// tslint:disable

import DelegateStaker from './delegate_staker'
import PosdaoEpoch from './posdao_epoch'

/**
 * rewards from delegate staking
 */
interface DelegateReward {
  id_delegator: DelegateStaker['id']
  id_node: Buffer & {readonly __brand?: 'delegate_reward_id_node'}
  id_posdao_epoch: PosdaoEpoch['id']
  /**
   * @default false
   */
  is_claimed: (boolean) | null
  reward_amount: (string) | null
}
export default DelegateReward;

/**
 * rewards from delegate staking
 */
interface DelegateReward_InsertParameters {
  id_delegator: DelegateStaker['id']
  id_node: Buffer & {readonly __brand?: 'delegate_reward_id_node'}
  id_posdao_epoch: PosdaoEpoch['id']
  /**
   * @default false
   */
  is_claimed?: (boolean) | null
  reward_amount?: (string) | null
}
export type {DelegateReward_InsertParameters}
