/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: venYLWVQ97HcNVthx1Lcl7T9PTnAl8GCXBHyPlrEuONMymw/zi3L8PCSq7FyBcgM2m8abmGe+YUlSID50AXyXQ==
 */

/* eslint-disable */
// tslint:disable

interface Headers {
  block_duration: number
  block_hash: string
  block_number: number & {readonly __brand?: 'headers_block_number'}
  block_time: Date
  extra_data: string
  transaction_count: number
  txs_per_sec: number
}
export default Headers;

interface Headers_InsertParameters {
  block_duration: number
  block_hash: string
  block_number: number & {readonly __brand?: 'headers_block_number'}
  block_time: Date
  extra_data: string
  transaction_count: number
  txs_per_sec: number
}
export type {Headers_InsertParameters}
