/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: lNj4HIfnaa9euIjskcNfwqdTShtbdOKszdR3ll4p5swcdX4SKyY4a4Pg3TgVfybeAMmQGkro+aU4kABGHR8QrA==
 */

/* eslint-disable */
// tslint:disable

interface Headers {
  block_duration: number
  block_hash: string
  block_number: number & {readonly __brand?: 'headers_block_number'}
  block_time: Date
  delta_pot: (string) | null
  extra_data: string
  governance_pot: (string) | null
  import_complete: (boolean) | null
  posdao_hbbft_epoch: (number) | null
  reinsert_pot: (string) | null
  reward_contract_total: (string) | null
  transaction_count: number
  txs_per_sec: number
  unclaimed_rewards: (string) | null
}
export default Headers;

interface Headers_InsertParameters {
  block_duration: number
  block_hash: string
  block_number: number & {readonly __brand?: 'headers_block_number'}
  block_time: Date
  delta_pot?: (string) | null
  extra_data: string
  governance_pot?: (string) | null
  import_complete?: (boolean) | null
  posdao_hbbft_epoch?: (number) | null
  reinsert_pot?: (string) | null
  reward_contract_total?: (string) | null
  transaction_count: number
  txs_per_sec: number
  unclaimed_rewards?: (string) | null
}
export type {Headers_InsertParameters}
