/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ObPEtr50XeUvEfsemoXcFXroYOkf5AFKMaxXwZejS1DsH6nbWhxaZvadU36W45qTdv68H89c+XtSHbK+CA0cAA==
 */

/* eslint-disable */
// tslint:disable

import Headers, {Headers_InsertParameters} from './headers'
import Node, {Node_InsertParameters} from './node'
import PosdaoEpoch, {PosdaoEpoch_InsertParameters} from './posdao_epoch'
import PosdaoEpochNode, {PosdaoEpochNode_InsertParameters} from './posdao_epoch_node'

interface DatabaseSchema {
  headers: {record: Headers, insert: Headers_InsertParameters};
  node: {record: Node, insert: Node_InsertParameters};
  posdao_epoch: {record: PosdaoEpoch, insert: PosdaoEpoch_InsertParameters};
  posdao_epoch_node: {record: PosdaoEpochNode, insert: PosdaoEpochNode_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Headers,
  Headers_InsertParameters,
  Node,
  Node_InsertParameters,
  PosdaoEpoch,
  PosdaoEpochNode,
  PosdaoEpochNode_InsertParameters,
  PosdaoEpoch_InsertParameters,
}
