/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1yMiDtY21Ha287HaNoVU8oD/HT8i8FyJrCZQiE2GUQS9expk1Hr3YDIc1Ng2l96WX90aG4MOKu/MYgdglImLtw==
 */

/* eslint-disable */
// tslint:disable

import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import AvailableEvent, {AvailableEvent_InsertParameters} from './available_event'
import BonusScoreHistory, {BonusScoreHistory_InsertParameters} from './bonus_score_history'
import DelegateReward, {DelegateReward_InsertParameters} from './delegate_reward'
import DelegateStaker, {DelegateStaker_InsertParameters} from './delegate_staker'
import Headers, {Headers_InsertParameters} from './headers'
import Node, {Node_InsertParameters} from './node'
import OrderedWithdrawal, {OrderedWithdrawal_InsertParameters} from './ordered_withdrawal'
import PendingValidatorStateEvent, {PendingValidatorStateEvent_InsertParameters} from './pending_validator_state_event'
import PosdaoEpoch, {PosdaoEpoch_InsertParameters} from './posdao_epoch'
import PosdaoEpochNode, {PosdaoEpochNode_InsertParameters} from './posdao_epoch_node'
import StakeDelegators, {StakeDelegators_InsertParameters} from './stake_delegators'
import StakeHistory, {StakeHistory_InsertParameters} from './stake_history'

interface DatabaseSchema {
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  available_event: {record: AvailableEvent, insert: AvailableEvent_InsertParameters};
  bonus_score_history: {record: BonusScoreHistory, insert: BonusScoreHistory_InsertParameters};
  delegate_reward: {record: DelegateReward, insert: DelegateReward_InsertParameters};
  delegate_staker: {record: DelegateStaker, insert: DelegateStaker_InsertParameters};
  headers: {record: Headers, insert: Headers_InsertParameters};
  node: {record: Node, insert: Node_InsertParameters};
  ordered_withdrawal: {record: OrderedWithdrawal, insert: OrderedWithdrawal_InsertParameters};
  pending_validator_state_event: {record: PendingValidatorStateEvent, insert: PendingValidatorStateEvent_InsertParameters};
  posdao_epoch: {record: PosdaoEpoch, insert: PosdaoEpoch_InsertParameters};
  posdao_epoch_node: {record: PosdaoEpochNode, insert: PosdaoEpochNode_InsertParameters};
  stake_delegators: {record: StakeDelegators, insert: StakeDelegators_InsertParameters};
  stake_history: {record: StakeHistory, insert: StakeHistory_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  AvailableEvent,
  AvailableEvent_InsertParameters,
  BonusScoreHistory,
  BonusScoreHistory_InsertParameters,
  DelegateReward,
  DelegateReward_InsertParameters,
  DelegateStaker,
  DelegateStaker_InsertParameters,
  Headers,
  Headers_InsertParameters,
  Node,
  Node_InsertParameters,
  OrderedWithdrawal,
  OrderedWithdrawal_InsertParameters,
  PendingValidatorStateEvent,
  PendingValidatorStateEvent_InsertParameters,
  PosdaoEpoch,
  PosdaoEpochNode,
  PosdaoEpochNode_InsertParameters,
  PosdaoEpoch_InsertParameters,
  StakeDelegators,
  StakeDelegators_InsertParameters,
  StakeHistory,
  StakeHistory_InsertParameters,
}
