/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 9H6gXHqwAE8zmdqiW0lPL4RgXCcJHMNAgEqVsTHeSzy/NMBdR99OYb2xvBomkxLeKN8DKlbLIDL0imT1gqiDeA==
 */

/* eslint-disable */
// tslint:disable

import AvailableEvent, {AvailableEvent_InsertParameters} from './available_event'
import DelegateReward, {DelegateReward_InsertParameters} from './delegate_reward'
import DelegateStaker, {DelegateStaker_InsertParameters} from './delegate_staker'
import Headers, {Headers_InsertParameters} from './headers'
import Node, {Node_InsertParameters} from './node'
import OrderedWithdrawal, {OrderedWithdrawal_InsertParameters} from './ordered_withdrawal'
import PendingValidatorStateEvent, {PendingValidatorStateEvent_InsertParameters} from './pending_validator_state_event'
import PosdaoEpoch, {PosdaoEpoch_InsertParameters} from './posdao_epoch'
import PosdaoEpochNode, {PosdaoEpochNode_InsertParameters} from './posdao_epoch_node'
import StakeHistory, {StakeHistory_InsertParameters} from './stake_history'

interface DatabaseSchema {
  available_event: {record: AvailableEvent, insert: AvailableEvent_InsertParameters};
  delegate_reward: {record: DelegateReward, insert: DelegateReward_InsertParameters};
  delegate_staker: {record: DelegateStaker, insert: DelegateStaker_InsertParameters};
  headers: {record: Headers, insert: Headers_InsertParameters};
  node: {record: Node, insert: Node_InsertParameters};
  ordered_withdrawal: {record: OrderedWithdrawal, insert: OrderedWithdrawal_InsertParameters};
  pending_validator_state_event: {record: PendingValidatorStateEvent, insert: PendingValidatorStateEvent_InsertParameters};
  posdao_epoch: {record: PosdaoEpoch, insert: PosdaoEpoch_InsertParameters};
  posdao_epoch_node: {record: PosdaoEpochNode, insert: PosdaoEpochNode_InsertParameters};
  stake_history: {record: StakeHistory, insert: StakeHistory_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AvailableEvent,
  AvailableEvent_InsertParameters,
  DelegateReward,
  DelegateReward_InsertParameters,
  DelegateStaker,
  DelegateStaker_InsertParameters,
  Headers,
  Headers_InsertParameters,
  Node,
  Node_InsertParameters,
  OrderedWithdrawal,
  OrderedWithdrawal_InsertParameters,
  PendingValidatorStateEvent,
  PendingValidatorStateEvent_InsertParameters,
  PosdaoEpoch,
  PosdaoEpochNode,
  PosdaoEpochNode_InsertParameters,
  PosdaoEpoch_InsertParameters,
  StakeHistory,
  StakeHistory_InsertParameters,
}
