/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ILfRjMTjYvZPO+OCch8n4P3r75MF2gamKqrqalhM294IXKIono2WYS1eI+yVrM02pcbZ/nxoT/Vyr9pbvRsHyg==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'

interface Node {
  added_block: Headers['block_number']
  diamond_name: (string) | null
  ens_name: (string) | null
  mining_address: Buffer
  mining_public_key: Buffer
  pool_address: Buffer & {readonly __brand?: 'node_pool_address'}
}
export default Node;

interface Node_InsertParameters {
  added_block: Headers['block_number']
  diamond_name?: (string) | null
  ens_name?: (string) | null
  mining_address: Buffer
  mining_public_key: Buffer
  pool_address: Buffer & {readonly __brand?: 'node_pool_address'}
}
export type {Node_InsertParameters}
