/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wq44/0P8UQaBU5cvHf5boy91mwQ97xZSE2FZZZFE7mUTjHp7IcGP+6CwMKJ1Vva27hEaR+QIz2BpBIsL0YPQ8Q==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'

interface Node {
  added_block: Headers['block_number']
  bonus_score: (number) | null
  diamond_name: (string) | null
  ens_name: (string) | null
  mining_address: Buffer
  mining_public_key: Buffer
  pool_address: Buffer & {readonly __brand?: 'node_pool_address'}
}
export default Node;

interface Node_InsertParameters {
  added_block: Headers['block_number']
  bonus_score?: (number) | null
  diamond_name?: (string) | null
  ens_name?: (string) | null
  mining_address: Buffer
  mining_public_key: Buffer
  pool_address: Buffer & {readonly __brand?: 'node_pool_address'}
}
export type {Node_InsertParameters}
