/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: LcKLzzZ0W9yQj78/q/bJ/e+m0/2MeRYzjDHrvRqyFjBO6ZspOS0Q9NnEpsbfoJYKl/IClHA7KxTBtzW19MY5hg==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'

interface Node {
  added_block: (Headers['block_number']) | null
  diamond_name: (string) | null
  ens_name: (string) | null
  mining_address: string
  mining_public_key: string
  pool_address: string & {readonly __brand?: 'node_pool_address'}
}
export default Node;

interface Node_InsertParameters {
  added_block?: (Headers['block_number']) | null
  diamond_name?: (string) | null
  ens_name?: (string) | null
  mining_address: string
  mining_public_key: string
  pool_address: string & {readonly __brand?: 'node_pool_address'}
}
export type {Node_InsertParameters}
