/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JErkPofz8QlRUqrcQHM4EUk8tFYWz4KSMs9S93vTjFvYttlbrqmBx/FSic2LaebvI1pYVgRJF3M4NWEepRl0gA==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'
import Node from './node'
import PosdaoEpoch from './posdao_epoch'

interface OrderedWithdrawal {
  amount: string
  block_number: (number) | null
  claimed_on_block: (Headers['block_number']) | null
  from_pool_stakingAddress: (Node['pool_address']) | null
  /**
   * @default nextval('ordered_withdrawal_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'ordered_withdrawal_id'}
  staker: (Buffer) | null
  staking_epoch: (PosdaoEpoch['id']) | null
}
export default OrderedWithdrawal;

interface OrderedWithdrawal_InsertParameters {
  amount: string
  block_number?: (number) | null
  claimed_on_block?: (Headers['block_number']) | null
  from_pool_stakingAddress?: (Node['pool_address']) | null
  /**
   * @default nextval('ordered_withdrawal_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'ordered_withdrawal_id'}
  staker?: (Buffer) | null
  staking_epoch?: (PosdaoEpoch['id']) | null
}
export type {OrderedWithdrawal_InsertParameters}
