/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: R2Slt2Kme9KVTM8FyaF/9HBfz9pSSLA5/qh8SVhtcEcEAEzolEbLrgOgSbgea/GgGTPisMFXEU+Le3hMC/zEPQ==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'
import Node from './node'
import PosdaoEpoch from './posdao_epoch'

interface OrderedWithdrawal {
  amount: string
  blockNumber: (number) | null
  claimedOnBlock: (Headers['block_number']) | null
  fromPoolStakingAddress: (Node['pool_address']) | null
  /**
   * @default nextval('"OrderedWithdrawal_id_seq"'::regclass)
   */
  id: number & {readonly __brand?: 'OrderedWithdrawal_id'}
  staker: (string) | null
  stakingEpoch: (PosdaoEpoch['id']) | null
}
export default OrderedWithdrawal;

interface OrderedWithdrawal_InsertParameters {
  amount: string
  blockNumber?: (number) | null
  claimedOnBlock?: (Headers['block_number']) | null
  fromPoolStakingAddress?: (Node['pool_address']) | null
  /**
   * @default nextval('"OrderedWithdrawal_id_seq"'::regclass)
   */
  id?: number & {readonly __brand?: 'OrderedWithdrawal_id'}
  staker?: (string) | null
  stakingEpoch?: (PosdaoEpoch['id']) | null
}
export type {OrderedWithdrawal_InsertParameters}
