/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5Y7pAmVGau8Tlgs85jmgTD/g6g+AdbV4w+vEAbUUWJZ/WQZhG1zMp8p4WdP7Yjc9AvTXiQmEZXjCP6HGc7X3vQ==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'

interface PendingValidatorStateEvent {
  keygen_round: number & {readonly __brand?: 'pending_validator_state_event_keygen_round'}
  node: Buffer & {readonly __brand?: 'pending_validator_state_event_node'}
  on_enter_block_number: Headers['block_number']
  on_exit_block_number: (Headers['block_number']) | null
  state: string & {readonly __brand?: 'pending_validator_state_event_state'}
}
export default PendingValidatorStateEvent;

interface PendingValidatorStateEvent_InsertParameters {
  keygen_round: number & {readonly __brand?: 'pending_validator_state_event_keygen_round'}
  node: Buffer & {readonly __brand?: 'pending_validator_state_event_node'}
  on_enter_block_number: Headers['block_number']
  on_exit_block_number?: (Headers['block_number']) | null
  state: string & {readonly __brand?: 'pending_validator_state_event_state'}
}
export type {PendingValidatorStateEvent_InsertParameters}
