/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: XE9shOo8H0oKnO5TIh/dLEN99i+nkmbZy87zg9uff8K27CSs6GCUzIqxzzFZbzw3X0fLybOhLnf580dTZcF5dA==
 */

/* eslint-disable */
// tslint:disable

import Node from './node'
import PendingValidatorState from './pending_validator_state'

interface PendingValidatorStateEvent {
  node: Node['pool_address']
  on_enter_block_number: number & {readonly __brand?: 'pending_validator_state_event_on_enter_block_number'}
  on_exit_block_number: (number) | null
  state: PendingValidatorState['id']
}
export default PendingValidatorStateEvent;

interface PendingValidatorStateEvent_InsertParameters {
  node: Node['pool_address']
  on_enter_block_number: number & {readonly __brand?: 'pending_validator_state_event_on_enter_block_number'}
  on_exit_block_number?: (number) | null
  state: PendingValidatorState['id']
}
export type {PendingValidatorStateEvent_InsertParameters}
