/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: AJQQFHocVVZJIDkq1AN0lVbvNKyYp4Sl6snGmMQI7L204FGaRSo51cr1ZwPMoz49I2CShbhfddgHa+ACIvzj0w==
 */

/* eslint-disable */
// tslint:disable

interface PendingValidatorState {
  id: number & {readonly __brand?: 'PendingValidatorState_id'}
  name: (string) | null
}
export default PendingValidatorState;

interface PendingValidatorState_InsertParameters {
  id: number & {readonly __brand?: 'PendingValidatorState_id'}
  name?: (string) | null
}
export type {PendingValidatorState_InsertParameters}
