/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: KXb/D9CqIF46KX5XNkkstIeUsNlirt5VGbYk3DM9HwSTv2V8fP9NHz6Mwp8Q5yj5qn33CBnwrpI9kgXs7ECYVw==
 */

/* eslint-disable */
// tslint:disable

interface PendingValidatorState {
  id: number & {readonly __brand?: 'pending_validator_state_id'}
  name: (string) | null
}
export default PendingValidatorState;

interface PendingValidatorState_InsertParameters {
  id: number & {readonly __brand?: 'pending_validator_state_id'}
  name?: (string) | null
}
export type {PendingValidatorState_InsertParameters}
