/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CanU8uaqdjjMy0ZNrowNhRG8lJHJX16OX+MQifdFte1X3cDjcDX53PrkhI1n47J+o5BdxxIgy0rI7iXsymZJpQ==
 */

/* eslint-disable */
// tslint:disable

import Node from './node'
import PosdaoEpoch from './posdao_epoch'

interface PosdaoEpochNode {
  id_node: Node['pool_address']
  id_posdao_epoch: PosdaoEpoch['id']
  /**
   * @default false
   */
  is_claimed: (boolean) | null
  owner_reward: (string) | null
}
export default PosdaoEpochNode;

interface PosdaoEpochNode_InsertParameters {
  id_node: Node['pool_address']
  id_posdao_epoch: PosdaoEpoch['id']
  /**
   * @default false
   */
  is_claimed?: (boolean) | null
  owner_reward?: (string) | null
}
export type {PosdaoEpochNode_InsertParameters}
