/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 7urDBTekcb9hEq41I2tNzrYYMnYgkF43fcQ4KsT/Oxs8gq9WLxNmvRqn4z5KF0zf45O1BjQz2NckZSvowHw9mA==
 */

/* eslint-disable */
// tslint:disable

import Node from './node'
import PosdaoEpoch from './posdao_epoch'

interface PosdaoEpochNode {
  epoch_apy: string
  id_node: Node['pool_address']
  id_posdao_epoch: PosdaoEpoch['id']
  /**
   * @default false
   */
  is_claimed: (boolean) | null
  owner_reward: (string) | null
}
export default PosdaoEpochNode;

interface PosdaoEpochNode_InsertParameters {
  epoch_apy: string
  id_node: Node['pool_address']
  id_posdao_epoch: PosdaoEpoch['id']
  /**
   * @default false
   */
  is_claimed?: (boolean) | null
  owner_reward?: (string) | null
}
export type {PosdaoEpochNode_InsertParameters}
