/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: apGMVJC/ymVkpYJIQscgYRXwc2+Wpb1O/sZmao8ms8y5L0WMVHnSc43n0BArmXYe6RZN5G/Y7/L/b6lin3FArw==
 */

/* eslint-disable */
// tslint:disable

import Node from './node'
import PosdaoEpoch from './posdao_epoch'

interface PosdaoEpochNode {
  id_node: (Node['pool_address']) | null
  id_posdao_epoch: (PosdaoEpoch['id']) | null
}
export default PosdaoEpochNode;

interface PosdaoEpochNode_InsertParameters {
  id_node?: (Node['pool_address']) | null
  id_posdao_epoch?: (PosdaoEpoch['id']) | null
}
export type {PosdaoEpochNode_InsertParameters}
