/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Go82BCtqVkQYqWCDs6PJPhg2sVy/bFz2y9sRV4CWYbojCgDp533YAI8XDRXh1p2aQNRnvh3hRXVil32mb0VfKw==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'

interface PosdaoEpoch {
  block_end: (Headers['block_number']) | null
  block_start: Headers['block_number']
  id: number & {readonly __brand?: 'posdao_epoch_id'}
}
export default PosdaoEpoch;

interface PosdaoEpoch_InsertParameters {
  block_end?: (Headers['block_number']) | null
  block_start: Headers['block_number']
  id: number & {readonly __brand?: 'posdao_epoch_id'}
}
export type {PosdaoEpoch_InsertParameters}
