/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1+6Ps45yMlp8WYufpaIDg9DijZDRyi6712QiscDt38KMZUrXD/qgsRfU51spZp/3Y2cG8tTRoEinq5Jyvuwx5Q==
 */

/* eslint-disable */
// tslint:disable

import Headers from './headers'
import Node from './node'

interface StakeHistory {
  from_block: Headers['block_number']
  node: Node['pool_address']
  stake_amount: string
  to_block: Headers['block_number']
}
export default StakeHistory;

interface StakeHistory_InsertParameters {
  from_block: Headers['block_number']
  node: Node['pool_address']
  stake_amount: string
  to_block: Headers['block_number']
}
export type {StakeHistory_InsertParameters}
