/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ZTMq31d59TpyuxmbB/TpK8KR9iPErCpgJnwZr3uezmvpN36STVQGlawgRSbTkP3CObdkjWpu2wMmpub+oi71sA==
 */

/* eslint-disable */
// tslint:disable

import Node from './node'

interface StakeDelegators {
  delegator: Buffer & {readonly __brand?: 'stake_delegators_delegator'}
  pool_address: Node['pool_address']
  total_delegated: string
}
export default StakeDelegators;

interface StakeDelegators_InsertParameters {
  delegator: Buffer & {readonly __brand?: 'stake_delegators_delegator'}
  pool_address: Node['pool_address']
  total_delegated: string
}
export type {StakeDelegators_InsertParameters}
