/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type ReverseConfirmed = ContractEventLog<{
  name: string;
  reverse: string;
  0: string;
  1: string;
}>;
export type ReverseRemoved = ContractEventLog<{
  name: string;
  reverse: string;
  0: string;
  1: string;
}>;

export interface IReverseRegistry extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IReverseRegistry;
  clone(): IReverseRegistry;
  methods: {
    hasReverse(_name: string | number[]): NonPayableTransactionObject<boolean>;

    getReverse(_name: string | number[]): NonPayableTransactionObject<string>;

    canReverse(_data: string): NonPayableTransactionObject<boolean>;

    reverse(_data: string): NonPayableTransactionObject<string>;
  };
  events: {
    ReverseConfirmed(cb?: Callback<ReverseConfirmed>): EventEmitter;
    ReverseConfirmed(
      options?: EventOptions,
      cb?: Callback<ReverseConfirmed>
    ): EventEmitter;

    ReverseRemoved(cb?: Callback<ReverseRemoved>): EventEmitter;
    ReverseRemoved(
      options?: EventOptions,
      cb?: Callback<ReverseRemoved>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "ReverseConfirmed", cb: Callback<ReverseConfirmed>): void;
  once(
    event: "ReverseConfirmed",
    options: EventOptions,
    cb: Callback<ReverseConfirmed>
  ): void;

  once(event: "ReverseRemoved", cb: Callback<ReverseRemoved>): void;
  once(
    event: "ReverseRemoved",
    options: EventOptions,
    cb: Callback<ReverseRemoved>
  ): void;
}
