/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IValidatorSetHbbft extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IValidatorSetHbbft;
  clone(): IValidatorSetHbbft;
  methods: {
    initialize(
      arg0: string,
      arg1: string,
      arg2: string,
      arg3: string,
      arg4: string[],
      arg5: string[]
    ): NonPayableTransactionObject<void>;

    finalizeChange(): NonPayableTransactionObject<void>;

    newValidatorSet(): NonPayableTransactionObject<void>;

    removeMaliciousValidators(
      arg0: string[]
    ): NonPayableTransactionObject<void>;

    setStakingAddress(
      arg0: string,
      arg1: string
    ): NonPayableTransactionObject<void>;

    handleFailedKeyGeneration(): NonPayableTransactionObject<void>;

    areDelegatorsBanned(arg0: string): NonPayableTransactionObject<boolean>;

    blockRewardContract(): NonPayableTransactionObject<string>;

    canCallAnnounceAvailability(
      _miningAddress: string
    ): NonPayableTransactionObject<boolean>;

    getPendingValidators(): NonPayableTransactionObject<string[]>;

    getPreviousValidators(): NonPayableTransactionObject<string[]>;

    getValidators(): NonPayableTransactionObject<string[]>;

    isReportValidatorValid(arg0: string): NonPayableTransactionObject<boolean>;

    isValidator(arg0: string): NonPayableTransactionObject<boolean>;

    isValidatorBanned(arg0: string): NonPayableTransactionObject<boolean>;

    isValidatorOrPending(arg0: string): NonPayableTransactionObject<boolean>;

    isPendingValidator(arg0: string): NonPayableTransactionObject<boolean>;

    getPendingValidatorKeyGenerationMode(
      arg0: string
    ): NonPayableTransactionObject<string>;

    MAX_VALIDATORS(): NonPayableTransactionObject<string>;

    miningByStakingAddress(arg0: string): NonPayableTransactionObject<string>;

    randomContract(): NonPayableTransactionObject<string>;

    reportMaliciousCallable(
      arg0: string,
      arg1: string,
      arg2: number | string | BN
    ): NonPayableTransactionObject<{
      0: boolean;
      1: boolean;
    }>;

    stakingByMiningAddress(arg0: string): NonPayableTransactionObject<string>;

    publicKeyByStakingAddress(
      arg0: string
    ): NonPayableTransactionObject<string>;

    getPublicKey(arg0: string): NonPayableTransactionObject<string>;

    stakingContract(): NonPayableTransactionObject<string>;

    getCurrentTimestamp(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
