{
 "title": "Hbbft2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(import_txs[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Up/Down",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", up)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Block Import",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "import_blocks", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "db_overlay_recent_backing_size", "legendFormat": "{{name}} backing size" },
    { "expr": "db_overlay_recent_journal_size", "legendFormat": "{{name}} journal" },
    { "expr": "db_overlay_recent_pending_size", "legendFormat": "{{name}} pending" },
    {
     "expr": "db_overlay_recent_transactions_size",
     "legendFormat": "{{name}} recent transactions"
    },
    {}
   ]
  },
  {
   "title": "Block",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "chain_block", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "code_cache_size", "legendFormat": "{{name}} code" },
    { "expr": "blockchaincache_block_recipts", "legendFormat": "{{name}} receipts" },
    { "expr": "blockchaincache_blocks", "legendFormat": "blocks" },
    { "expr": "blockchaincache_size", "legendFormat": "size" },
    { "expr": "blockchaincache_txaddrs", "legendFormat": "txaddrs" }
   ]
  },
  {
   "title": "Block Details cache",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "blockchaincache_block_details{job=\"remotenet\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "cached accounts",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "targets": [
    { "expr": "account_cache_len", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Key-Value Database",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "kvdb_bytes_read", "legendFormat": "{{name}} read" },
    { "expr": "kvdb_bytes_written", "legendFormat": "{{name}} write" }
   ]
  },
  {
   "title": "Import",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(import_blocks[$__rate_interval])",
     "legendFormat": "{{name}} import blocks"
    },
    {
     "expr": "rate(import_gas[$__rate_interval]) / 1000",
     "legendFormat": "import gas"
    },
    {
     "expr": "rate(import_txs[$__rate_interval])",
     "legendFormat": "{{name}} transactions per second"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 65 },
   "targets": [
    { "expr": "net_peers", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Peers Active",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "net_active_peers{job=\"remotenet\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 78 },
   "targets": [
    { "expr": "queue_size_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "queue_mem_used", "legendFormat": "{{name}} mem used" },
    { "expr": "queue_size_total", "legendFormat": "{{name}} size total" },
    { "expr": "queue_size_unverified", "legendFormat": "{{name}} unverified" },
    { "expr": "queue_size_verifying", "legendFormat": "{{name}} verifying" },
    { "expr": "queue_size_verified", "legendFormat": "{{name}} verified" }
   ]
  }
 ]
}