{
 "title": "DMD DB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Transactions per Second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT block_time, txs_per_sec FROM headers "
    }
   ]
  },
  {
   "title": "Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT block_time, transaction_count FROM headers LIMIT null "
    },
    {
     "rawSql": "SELECT block_time FROM headers LIMIT null "
    }
   ]
  },
  {
   "title": "Bock Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT block_duration, block_time FROM headers "
    }
   ]
  }
 ]
}