{
 "title": "Hbbft2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Block Details cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    { "expr": "blockchaincache_block_details", "legendFormat": "cache" }
   ]
  },
  {
   "title": "Block Import",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "targets": [
    { "expr": "import_blocks", "legendFormat": "number of imorted bocks" },
    { "expr": "chain_block", "legendFormat": "block height" }
   ]
  },
  {
   "title": "Key-Value Database",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "kvdb_bytes_read", "legendFormat": "read" },
    { "expr": "kvdb_bytes_written", "legendFormat": "write" }
   ]
  },
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "db_overlay_recent_backing_size", "legendFormat": "backing size" },
    { "expr": "db_overlay_recent_journal_size", "legendFormat": "journal" },
    { "expr": "db_overlay_recent_pending_size", "legendFormat": "pending" },
    {
     "expr": "db_overlay_recent_transactions_size",
     "legendFormat": "recent transactions"
    },
    {}
   ]
  },
  {
   "title": "Import",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(import_blocks[$__rate_interval])",
     "legendFormat": "import blocks"
    },
    {
     "expr": "rate(import_gas[$__rate_interval]) / 1000",
     "legendFormat": "import gas"
    },
    {
     "expr": "rate(import_txs[$__rate_interval])",
     "legendFormat": "transactions per second"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "code_cache_size", "legendFormat": "code" },
    { "expr": "blockchaincache_block_recipts", "legendFormat": "receipts" },
    { "expr": "blockchaincache_blocks", "legendFormat": "blocks" },
    { "expr": "blockchaincache_size", "legendFormat": "size" },
    { "expr": "blockchaincache_txaddrs", "legendFormat": "txaddrs" }
   ]
  },
  {
   "title": "cached accounts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 55 },
   "targets": [
    { "expr": "account_cache_len", "legendFormat": "account cache length" }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 64 },
   "targets": [
    { "expr": "net_active_peers", "legendFormat": "active peers" },
    { "expr": "net_peers", "legendFormat": "peers" }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 72 },
   "targets": [
    { "expr": "queue_mem_used", "legendFormat": "mem used" },
    { "expr": "queue_size_total", "legendFormat": "size total" },
    { "expr": "queue_size_unverified", "legendFormat": "unverified" },
    { "expr": "queue_size_verifying", "legendFormat": "verifying" },
    { "expr": "queue_size_verified", "legendFormat": "verified" }
   ]
  }
 ]
}