{
 "title": "Hbbft_Messages",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(name)" } },
   { "name": "other_node", "label": "other node", "query": { "query": "label_values(other_node)" } }
  ]
 },
 "panels": [
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "last_message_good",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "last_message_good{name=~\"$node\", other_node=~\"$other_node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "last_message_faulty",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "last_message_faulty{other_node=~\"$other_node\", name=~\"$node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Sealing Blocks Bad",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sealing_blocks_bad{name=~\"$node\", other_node=~\"$other_node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "last_good_sealing_message",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "last_good_sealing_message{name=~\"$node\", other_node=~\"$other_node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "Sealing Blocks Late",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sealing_blocks_late{name=~\"$node\", other_node=~\"$other_node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "Sealing Blocks Late",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sealing_blocks_late{name=~\"$node\", other_node=~\"$other_node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "Cumulitive Lateness",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "cumulative_lateness{name=~\"$node\", other_node=~\"$other_node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "Cumulitive Lateness",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "cumulative_lateness{name=~\"$node\", other_node=~\"$other_node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "Cumulitive Lateness",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 137 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cumulative_lateness{name=~\"$node\", other_node=~\"$other_node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "Last Late Sealing Message",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 154 },
   "targets": [
    {
     "expr": "last_late_sealing_message{name=~\"$node\", other_node=~\"$other_node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "Epoch Start Blocks",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "staking_epoch_start_block{name=~\"$node\"}",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  },
  {
   "title": "Epoch Block Number",
   "type": "timeseries",
   "description": "Blocks since last epoch start",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 185 },
   "targets": [
    {
     "expr": "chain_block{name=~\"$node\"} - staking_epoch_start_block",
     "legendFormat": "{{name}} {{other_node}}"
    }
   ]
  }
 ]
}