{
 "title": "Network",
 "time": { "from": "2023-09-09T19:35:14.727Z", "to": "2023-09-09T22:03:08.213Z" },
 "panels": [
  {
   "title": "Total blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(block_number) FROM headers LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average timings",
   "type": "stat",
   "description": "Average block and epoch time based on last 1000 blocks / last 100 epochs",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(durations.block_duration)\nFROM (SELECT block_duration FROM headers WHERE block_number > 1 ORDER BY block_number DESC LIMIT 1000) as durations;"
    },
    {
     "rawSql": "select\n  avg(durations.epoch_duration)\nfrom (\n  select \n    id as epoch,\n    EXTRACT(EPOCH FROM end_block.block_time - start_block.block_time)::int as epoch_duration\n  from posdao_epoch as epochs\n  join headers as start_block on epochs.block_start = start_block.block_number\n  join headers as end_block on epochs.block_end = end_block.block_number\n  where id > 0\n  order by id desc\n  limit 100\n) as durations;"
    }
   ]
  },
  {
   "title": "Transactions statistic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(transaction_count) FROM headers;"
    },
    {
     "rawSql": "SELECT SUM(transaction_count) FROM headers;"
    }
   ]
  },
  {
   "title": "Current validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(*)\nfrom\n  pending_validator_state_event\nwhere\n  state = 'current'\n  and on_exit_block_number is null;"
    }
   ]
  },
  {
   "title": "Block Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  block_time,\n  block_number\nFROM\n  headers\nWHERE\n  $__timeFilter(block_time)\nORDER BY\n  block_number DESC"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  posdao_hbbft_epoch as epoch,\n  block_time\nFROM\n  headers\nWHERE\n  $__timeFilter(block_time)\nORDER BY\n  posdao_hbbft_epoch DESC\n"
    }
   ]
  },
  {
   "title": "Block Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT block_duration, block_time FROM headers WHERE block_number > 1 AND $__timeFilter(block_time);"
    }
   ]
  },
  {
   "title": "Epoch duration",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n  id as epoch,\n  EXTRACT(EPOCH FROM end_block.block_time - start_block.block_time)::int as epoch_duration\nfrom posdao_epoch as epochs\njoin headers as start_block on epochs.block_start = start_block.block_number\njoin headers as end_block on epochs.block_end = end_block.block_number\nwhere id > 0\norder by id desc\nlimit 100;"
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "rawSql": "SELECT block_time, txs_per_sec FROM headers WHERE $__timeFilter(block_time);"
    }
   ]
  },
  {
   "title": "Transactions count per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT block_time, transaction_count FROM headers WHERE $__timeFilter(block_time);"
    }
   ]
  }
 ]
}