{
 "title": "Hbbft3",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Is syncing",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(is_major_syncing)", "legendFormat": "__auto" },
    { "expr": "sum(is_syncing)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Up/Down",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", up)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Import",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(import_txs[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "status-history",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "up{job=\"beta1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_block", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Import",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 60 },
   "targets": [
    { "expr": "rate(import_blocks[1m])", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 60 },
   "targets": [
    { "expr": "chain_block", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Details cache",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "blockchaincache_block_details{job=\"beta1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "db_overlay_recent_backing_size", "legendFormat": "{{name}} backing size" },
    { "expr": "db_overlay_recent_journal_size", "legendFormat": "{{name}} journal" },
    { "expr": "db_overlay_recent_pending_size", "legendFormat": "{{name}} pending" },
    {
     "expr": "db_overlay_recent_transactions_size",
     "legendFormat": "{{name}} recent transactions"
    },
    {}
   ]
  },
  {
   "title": "Key-Value Database",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "kvdb_bytes_read", "legendFormat": "{{name}} read" },
    { "expr": "kvdb_bytes_written", "legendFormat": "{{name}} write" }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "code_cache_size", "legendFormat": "{{name}} code" },
    { "expr": "blockchaincache_block_recipts", "legendFormat": "{{name}} receipts" },
    { "expr": "blockchaincache_blocks", "legendFormat": "blocks" },
    { "expr": "blockchaincache_size", "legendFormat": "size" },
    { "expr": "blockchaincache_txaddrs", "legendFormat": "txaddrs" }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 97 },
   "targets": [
    { "expr": "net_peers", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Peers Active",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 97 },
   "targets": [
    { "expr": "net_active_peers", "legendFormat": "{{name}} active" },
    { "expr": "net_peers", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 110 },
   "targets": [
    { "expr": "queue_size_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "queue_mem_used", "legendFormat": "{{name}} mem used" },
    { "expr": "queue_size_total", "legendFormat": "{{name}} size total" },
    { "expr": "queue_size_unverified", "legendFormat": "{{name}} unverified" },
    { "expr": "queue_size_verifying", "legendFormat": "{{name}} verifying" },
    { "expr": "queue_size_verified", "legendFormat": "{{name}} verified" }
   ]
  },
  {
   "title": "cached accounts",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 123 },
   "targets": [
    { "expr": "account_cache_len", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Import",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "rate(import_blocks[$__rate_interval])",
     "legendFormat": "{{name}} import blocks"
    },
    {
     "expr": "rate(import_gas[$__rate_interval]) / 1000",
     "legendFormat": "import gas"
    },
    {
     "expr": "rate(import_txs[$__rate_interval])",
     "legendFormat": "{{name}} transactions per second"
    }
   ]
  }
 ]
}