{
 "title": "Staking",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "active_pools",
    "label": "Active pools",
    "query": "select distinct '0x' || encode(stake_history.node::bytea, 'hex') from stake_history where stake_amount > 0;"
   }
  ]
 },
 "panels": [
  {
   "title": "Staking pools statistics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  COUNT(distinct node)\nfrom\n  stake_history\nwhere\n  stake_amount > 0\n  and from_block = to_block;"
    },
    {
     "rawSql": "select\n  SUM(stake_amount)\nfrom\n  stake_history\nwhere\n  from_block = to_block;"
    },
    {
     "rawSql": "select\n  COALESCE(sum(total_delegated), 0) as delegated_stake\nfrom\n  stake_delegators;"
    },
    {
     "rawSql": "SELECT SUM(owner_reward) FROM posdao_epoch_node;"
    }
   ]
  },
  {
   "title": "Past month epochs count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tcount(*) as past_month_epochs\nfrom posdao_epoch e\njoin headers h_start on e.block_start = h_start.block_number\nwhere DATE_PART('day', now()::timestamp -  h_start.block_time::timestamp) < 31;\n"
    }
   ]
  },
  {
   "title": "Average epoch reward",
   "type": "xychart",
   "description": "Average epoch reward based on last 100 epochs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select\n  epochs.id_posdao_epoch,\n  avg(rewards.owner_reward) as average_epoch_reward\nfrom\n  posdao_epoch_node epochs\n  join posdao_epoch_node rewards on epochs.id_posdao_epoch = rewards.id_posdao_epoch\ngroup by\n  epochs.id_posdao_epoch\norder by\n  epochs.id_posdao_epoch desc\nlimit\n  100"
    }
   ]
  },
  {
   "title": "Stake/Rewards of $active_pools",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 16 },
   "repeat": "active_pools",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  stake_amount\nfrom\n  stake_history\nwhere\n  from_block = to_block\n  and '0x' || encode(node :: bytea, 'hex') = $active_pools;"
    },
    {
     "rawSql": "select\n  sum(owner_reward) as total_rewards\nfrom\n  posdao_epoch_node\nwhere '0x' || encode(id_node :: bytea, 'hex') = $active_pools;"
    },
    {
     "rawSql": "select\n  COALESCE(sum(owner_reward), 0) as claimed_rewards\nfrom\n  posdao_epoch_node\nwhere '0x' || encode(id_node :: bytea, 'hex') = $active_pools and is_claimed;"
    },
    {
     "rawSql": "select\n  count(distinct delegator)\nfrom\n  stake_delegators\nwhere\n  '0x' || encode(pool_address :: bytea, 'hex') = $active_pools;"
    },
    {
     "rawSql": "select\n  COALESCE(sum(total_delegated), 0) as delegated_stake\nfrom\n  stake_delegators\nwhere\n  '0x' || encode(pool_address :: bytea, 'hex') = $active_pools;"
    }
   ]
  },
  {
   "title": "Past month participation of $active_pools",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "repeat": "active_pools",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(en.id_posdao_epoch) epochs_participated\nfrom\n  posdao_epoch_node en\n  join posdao_epoch e on en.id_posdao_epoch = e.id\n  join headers h_start on e.block_start = h_start.block_number\nwhere\n  DATE_PART(\n    'day',\n    now() :: timestamp - h_start.block_time :: timestamp\n  ) < 31\n  and '0x' || encode(en.id_node :: bytea, 'hex') = $active_pools;"
    },
    {
     "expression": "($epoch_participation * 100) / $past_month_epochs_count",
     "type": "math"
    }
   ]
  }
 ]
}