{
 "title": "Validators",
 "time": { "from": "2024-12-04", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "validators",
    "label": "Validators",
    "query": "select distinct ('0x' || encode(node::bytea, 'hex')) as node from available_event;"
   }
  ]
 },
 "panels": [
  {
   "title": "Validators statistic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*)\nfrom pending_validator_state_event WHERE on_exit_block_number is NULL and state = 'current';"
    },
    {
     "rawSql": "SELECT\n  count(*)\nFROM\n  available_event ae\n  INNER JOIN (\n    SELECT\n      node,\n      MAX(block) block\n    FROM\n      available_event\n    GROUP BY\n      node\n  ) ae_max ON ae.node = ae_max.node\n  AND ae.block = ae_max.block\nwhere\n  became_available = true;"
    },
    {
     "rawSql": "SELECT\n  count(*)\nFROM\n  available_event ae\n  INNER JOIN (\n    SELECT\n      node,\n      MAX(block) block\n    FROM\n      available_event\n    GROUP BY\n      node\n  ) ae_max ON ae.node = ae_max.node\n  AND ae.block = ae_max.block\nwhere\n  became_available = false;"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  posdao_hbbft_epoch as epoch,\n  block_time\nFROM\n  headers\nWHERE\n  $__timeFilter(block_time)\nORDER BY\n  posdao_hbbft_epoch DESC\n"
    }
   ]
  },
  {
   "title": "Validators mode",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  HEADERS.BLOCK_TIME as \"time\",\n  case\n    when count(VALIDATOR_STATE.NODE) > 1 then 'keygen'\n    else 'default'\n  end as validators_mode\nFROM\n  HEADERS\n  LEFT JOIN PENDING_VALIDATOR_STATE_EVENT VALIDATOR_STATE ON VALIDATOR_STATE.STATE = 'pending'\n  AND (\n    headers.block_number >= VALIDATOR_STATE.on_enter_block_number\n    and (\n      (VALIDATOR_STATE.on_exit_block_number is null)\n      or (\n        headers.block_number <= VALIDATOR_STATE.on_exit_block_number\n      )\n    )\n  )\nWHERE\n  $__timeFilter(HEADERS.BLOCK_TIME)\ngroup by\n  headers.block_number\nORDER BY\n  HEADERS.BLOCK_NUMBER DESC"
    }
   ]
  },
  {
   "title": "Availability timeline changes",
   "type": "state-timeline",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 22 },
   "repeat": "validators",
   "targets": [
    {
     "rawSql": "select\n\th.block_time,\n\t'0x1' || encode(ae.node::bytea, 'hex') as node,\n\tae.became_available as n\nfrom available_event ae\ninner join headers h on ae.block = h.block_number\nwhere $__timeFilter(h.block_time) \norder by h.block_time desc;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "select\n\th.block_time,\n\t'0x1' || encode(ae.node::bytea, 'hex') as node,\n\t'0x1' || encode(ae.node::bytea, 'hex') as node2,\n\tae.became_available as n\nfrom available_event ae\ninner join headers h on ae.block = h.block_number\nwhere $__timeFilter(h.block_time) \norder by h.block_time desc;"
    }
   ]
  }
 ]
}